# ----------------------------------------------------------------------------------------------------
# Template to add Azure Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: 'myVariableGroup'
- name: environmentName
  default: 'DEV'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: SecurityScanDeployment
  displayName: Initialize Security Scan Deploy
  environment: ${{ parameters.environmentName }}

- job: SecurityScanJob
  displayName: Security Scan Job
  
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentName
      value: ${{ parameters.environmentName }}

  steps:
  - bash: |
      runScanLower=$(echo "$(runSecurityDevOpScan)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=runScanLower]$runScanLower"
    displayName: 'Create Variables'
    continueOnError: true

  - bash: |
      echo "environmentName=$(environmentName)"
      echo "runSecurityDevOpScan=$(runSecurityDevOpScan)"
      echo "runScanLower=$(runScanLower)"
    displayName: 'Display Variables'

  - task: UseDotNet@2
    condition: eq(variables.runScanLower, 'true')
    displayName: 'Use dotnet 3.1'
    inputs:
      version: 3.1.x
      
  - task: UseDotNet@2
    condition: eq(variables.runScanLower, 'true')
    displayName: 'Use dotnet 6.0'
    inputs:
      version: 6.0.x

  - task: MicrosoftSecurityDevOps@1
    condition: eq(variables.runScanLower, 'true')
    displayName: 'Run Microsoft Security DevOps'
    continueOnError: true
