# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build Test Utility; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: projectPath
  default: 'src/myFolderName/'
- name: solutionName
  default: 'myProjectName.sln'
- name: projectName
  default: 'myProjectName.csproj'
- name: projectExtension
  default: 'csproj'
- name: exeName
  default: 'myExeName'
- name: folderName
  default: 'myFolderName'
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'

# ------------------------------------------------------------------------------------------------------------------------
stages:
- stage: BuildTester
  displayName: Build Tester
  jobs:
  - ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
        appFolderName: ${{ parameters.folderName }}
        appSolutionName: ${{ parameters.solutionName }}
        appProjectFolderName: ${{ parameters.folderName }}
        appProjectExtension: ${{ parameters.projectExtension }}

  - template: templates/console-app-build-template.yml
    parameters:
      environmentName: 'DEV'
      projectPath: ${{ parameters.projectPath }}
      solutionName: ${{ parameters.solutionName }}
      projectName: ${{ parameters.projectName }}
      exeName: ${{ parameters.exeName }}
      folderName: ${{ parameters.folderName }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployTester${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Tester
    jobs:
    - template: templates/console-app-deploy-template.yml
      parameters:
        environmentName: ${{ environmentName }}
