# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    # - ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
    # - ${{ else }}:
    #   - job: ScanSkippedJob
    #     displayName: Skipping Scan

# ----------------------------------------------------------------------------------------------------
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/build-function-template.yml
    parameters:
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-function-template.yml
      parameters:
        environmentName: ${{ environmentName }}
