# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectFolderName
  default: ''
- name: appProjectName
  default: ''
- name: appProjectExtension
  default: 'csproj'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - ${{ if or(ne(lower(parameters.runMSDevSecOpsScan), 'none'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
        appFolderName: ${{ parameters.appFolderName }}
        appSolutionName: ${{ parameters.appSolutionName }}
        appProjectFolderName: ${{ parameters.appProjectFolderName }}
        appProjectExtension: ${{ parameters.appProjectExtension }}

  - template: templates/build-function-template.yml
    parameters:
      environmentName: 'DEV'
      appFolderName: ${{ parameters.appFolderName }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-function-template.yml
      parameters:
        environmentName: ${{ environmentName }}
