# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runDevSecOpsScan
  default: 'false'
- name: runGHAzDOScan
  default: 'false'
- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - ${{ if or(ne(lower(parameters.runDevSecOpsScan), 'none'), eq(lower(parameters.runGHAzDOScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
        workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
        workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

  - template: templates/build-function-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'
      workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
      workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-function-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
