# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Azure Resources and Application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectFolderName
  default: ''
- name: appProjectExtension
  default: 'csproj'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
        appFolderName: ${{ parameters.appFolderName }}
        appSolutionName: ${{ parameters.appSolutionName }}
        appProjectFolderName: ${{ parameters.appProjectFolderName }}
        appProjectExtension: ${{ parameters.appProjectExtension }}

  - template: templates/build-function-template.yml
    parameters:
      environmentName: 'DEV'
      appFolderName: ${{ parameters.appFolderName }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfrastructure${{ environmentName }}
    displayName: ${{ environmentName }} Infrastructure
    dependsOn: BuildApplication
    condition: succeeded('BuildApplication')
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        environmentName: ${{ environmentName }}

  - stage: Deploy${{ environmentName }}App
    displayName: Deploy ${{ environmentName }} App
    dependsOn: CreateInfrastructure${{ environmentName }}
    condition: succeeded('CreateInfrastructure${{ environmentName }}')
    jobs:
    - template: templates/deploy-function-template.yml
      parameters:
        environmentName: ${{ environmentName }}
