# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    # - ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
    # - ${{ else }}:
    #   - job: ScanSkippedJob
    #     displayName: Skipping Scan

- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfra${{ environmentName }}
    displayName: Create ${{ environmentName }} Resources
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        environmentName: ${{ environmentName }}
