# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: runMSDevSecOpsScan
  default: 'None'
- name: runGHASScan
  default: 'false'
- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'
- name: workingDirectoryIgnore
  default: '/docs'
- name: continueOnScanError
  default: 'true'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: ScanApplication
  displayName: Scan Application
  jobs:
  - template: templates/scan-code-template.yml
    parameters:
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
      workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
      workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}
      workingDirectoryIgnore: ${{ parameters.workingDirectoryIgnore }}
      #continueOnScanError: ${{ parameters.continueOnScanError }}
