# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build Test Utility; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'

# ------------------------------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
      - template: templates/scan-code-template.yml
        parameters:
          environmentName: 'DEV'
          runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
          runGHASScan: ${{ parameters.runGHASScan }}
          codeSection: 'console'

# ----------------------------------------------------------------------------------------------------
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/console-app-build-template.yml
    parameters:
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployTester${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Tester
    jobs:
    - template: templates/console-app-deploy-template.yml
      parameters:
        environmentName: ${{ environmentName }}
