# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Function App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra.and.function
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  # scan-code:
  #   name: Scan Source Code
  #   uses: ./.github/workflows/template-scan-code.yml

# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Function App
    uses: ./.github/workflows/template-function-app-build.yml
    secrets: inherit
    with:
      envCode: 'demo'
      rootDirectory: 'src/AzureFunctionsDemo'

# ------------------------------------------------------------------------------------------------------------------------
  infra-demo:
    name: Create Demo Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'demo'

  # infra-qa:
  #   name: Create QA Infra
  #   needs: infra-demo
  #   uses: ./.github/workflows/template-create-infra.yml
  #   secrets: inherit
  #   with:
  #     envCode: 'qa'

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app-demo:
    name: Deploy Demo App
    needs: infra-demo
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'demo'

  # deploy-app-qa:
  #   name: Deploy QA App
  #   needs: deploy-app-demo
  #   uses: ./.github/workflows/template-function-app-deploy.yml
  #   secrets: inherit
  #   with:
  #     envCode: 'qa'
