# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  infra-demo:
    name: Create Infra
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'demo'
      location: 'eastus'
      storageSku: 'Standard_LRS'
      functionAppSku: 'Y1'
      functionAppSkuFamily: 'Y'
      functionAppSkuTier: 'Dynamic'

  # infra-dev:
  #   name: Create DEV Infra
  #   needs: infra-demo
  #   uses: ./.github/workflows/template-create-infra.yml
  #   secrets: inherit
  #   with:
  #     envCode: 'dev'
  #     location: 'eastus'
  #     storageSku: 'Standard_LRS'
  #     functionAppSku: 'Y1'
  #     functionAppSkuFamily: 'Y'
  #     functionAppSkuTier: 'Dynamic'
