# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to scan files for security issues
# ------------------------------------------------------------------------------------------------------------------------
name: template.scan.code
on:
  workflow_call:
  
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scanner:
    runs-on: ubuntu-latest  #windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x

    - name: Run MS SecDevOps Analysis
      continue-on-error: true
      uses: microsoft/security-devops-action@preview
      id: msdo

    - name: Upload MS SecDevOps alerts to Security tab
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}