# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy a Function App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.app
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  build-app:
    name: Build Artifacts
    uses: ./.github/workflows/template-function-app-build.yml
    with:
      envCode: 'gha'
      rootDirectory: 'src/Durable.Demo'
    secrets: inherit

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app:
    name: Deploy App
    needs: [build-app]
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'demo'

  # deploy-app-qa:
  #   name: Deploy QA App
  #   needs: [deploy-app]
  #   uses: ./.github/workflows/template-function-app-deploy.yml
  #   secrets: inherit
  #   with:
  #     envCode: 'qa'
