# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: variableGroupName
  default: 'myVariableGroupName'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildApplication
  displayName: Build Application
  jobs:
  #- template: templates/secure-devops-template.yml
  #  parameters:
  #    variableGroupName: ${{ parameters.variableGroupName }}
  #    environmentName: 'DEV'

  - template: templates/build-logicstd-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEMO'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-logicstd-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
