# ----------------------------------------------------------------------------------------------------
# Pipeline to deploy a Function App
# See readme file for info about variable group "Dadabase.Function.Keys"
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: Dadabase.Function.Keys

# ----------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - FunctionApp
  #   exclude: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'
  #     - '**/*.md'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployMultiStage
    displayName: Multi-Stage Deploy
    type: boolean
    default: false
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployMultiStage), 'false') }}:
  - template: pipes/function-only-pipe.yml
    parameters:
      environments: ['DEMO']
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

- ${{ if eq(lower(parameters.deployMultiStage), 'true') }}:
  - template: pipes/function-only-pipe.yml
    parameters:
      variableGroupName: 'Dadabase.Function.Keys'
      environments: ['DEV','PROD']
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
