# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about variable group "FunctionDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: FunctionDemo

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployMultiStage
    displayName: Multi-Stage Deploy
    type: boolean
    default: false
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployMultiStage), 'false') }}:
  - template: pipes/infra-only-pipe.yml
    parameters:
      environments: ['DEMO']
      appFolderName: 'src/Function.Demo'
      appSolutionName: 'Function.Demo'
      appProjectFolderName: 'src/Function.Demo'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

- ${{ if eq(lower(parameters.deployMultiStage), 'true') }}:
  - template: pipes/infra-only-pipe.yml
    parameters:
      environments: ['DEV','QA']
      appFolderName: 'src/Function.Demo'
      appSolutionName: 'Function.Demo'
      appProjectFolderName: 'src/Function.Demo'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}