# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to Run Scan Utilities
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest # windows-latest

# ----------------------------------------------------------------------------------------------------
trigger:
 - none
  # batch: true
  # branches:
  #   include:
  #     - main

schedules:
- cron: '0 12 * * 3'
  displayName: Scan Every Wednesday
  branches:
    include:
    - main

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: string
    values:
      - None
      - Scan_Everything
      - Scan_Code_All_Folders
      - Scan_Infra_All_Folders
      - Scan_Code_One_Folder
      - Scan_Infra_One_Folder
      - Scan_Infra_Folder_For_Code
      - Scan_Code_Folder_For_Infra
      - All_Of_The_Above
    default: Scan_Everything
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/scan-code-pipe.yml
  parameters:
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
    workingDirectoryCode: 'src/Durable.Demo'
    workingDirectoryInfra: '/infra/bicep'
    workingDirectoryIgnore: '/docs'
    #continueOnScanError: 'true'
