# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy an already built Function App to Azure
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.deploy.function
run-name: Deploy Function App
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ inputs.envCode }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: functionapp

    # - name: List Files
    #   run: 
    #     tree ${{ env.GITHUB_ACTION_PATH }}
    #   continue-on-error: true

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy package to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.APP_NAME }}-${{ inputs.envCode }}
        package: .
